# spring
spring :
  datasource :
    url : jdbc:mysql://132.226.171.63:3306/fyodb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  main :
    banner-mode : console # banner 출력
  jpa :
    properties :
      hibernate :
        "[format_sql]" : true # sql 정렬 옵션

# logging
logging :
  level :
    com :
      fyo : debug