# spring
spring :
  main :
    banner-mode : console # banner 출력
  datasource :
    url : jdbc:mysql://192.168.56.101:3306/fyodb
  jpa :
    properties :
      hibernate :
        "[format_sql]" : true # sql 정렬 옵션

# logging
logging :
  level :
    com :
      fyo : debug